#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/3f6181c4-67ba-48bc-bc66-36a45647e97f # 
title: Policy Quote to Bind Process API
version: 1.0

uses: 
  submissiontype: /exchange_modules/4d34a677-fff8-40b2-896b-024389cae4de/submission-data-type/1.0.5/submission-data-type.raml
  accounttype: /exchange_modules/4d34a677-fff8-40b2-896b-024389cae4de/account-data-type/1.0.0/account-data-type.raml

  
/submission:
  post:
    description: Create a new Policy Submission
    body: 
      application/json:
        properties: 
          submission: submissiontype.Submission
          account: accounttype.account
        example:
          account: !include /exchange_modules/4d34a677-fff8-40b2-896b-024389cae4de/account-data-example/1.0.2/account-data-example.raml
          submission: !include /exchange_modules/4d34a677-fff8-40b2-896b-024389cae4de/submission-data-example/1.0.7/submission-data-example.raml
                  
    responses: 
      200:
        body: 
          application/json:
            example: |
              {
              "message": "successful"
              }
  get:
    description: Get the status of submissions
    responses: 
        200:
          body: 
            application/json:


