#%RAML 1.0 NamedExample

      AffinityBusinessCd: "NE"
      BranchOfficeCd: "3"
      BusinessSegmentCd: "00FL"
      DistributionChannelCd: "1"
      SubmissionEffDt: "2017-07-18T00:00:00-04:00"
      SubmissionExpDt: "2017-08-24T00:00:00-04:00"
      SubmissionReceivedDt: "2017-08-08T17:54:59-04:00"
      SubmittedLOBCd: "2"
      MarketSegmentCd: "23"
      WINSAgentCd: "FL191"
      QuotedPremiumAmt: "0"
      NAICSCd: "524210"
      QuotedLOBCd: "2"
      SubmissionQuotedDt: "2017-07-14T17:54:59-04:00"
      SubmissionStatusCd: "4"
      SubmissionTypeCd: "1"
      CarrierCd: "16"
      UnderwriterAssistantCd: "102"
      UnderwriterCd: "206"
      StateAbbrCd: "NY"
      SubmittedExcessPrimary: "P"
      QuotedExcessPrimary: "P"
      SubProducerCd: "UA001"
      IsPublicPrivateInd: "true"
