#%RAML 1.0 NamedExample


  accountNumber: "589474"
  accountVersionNumber: "1"
  email: "912147"
  billingAddress:
    addressline1: "1 First Ave."
    city: "New York"
    state: "New York"
    zip: "10001"  
  shippingAddress: 
    addressline1: "1 First Ave."
    city: "New York"
    state: "New York"
    zip: "10001"  
  name: "Mythical Company"
  overOFACblock: "false"
  active: "Y"
