#%RAML 1.0 Library
usage: Defines the standard structure of Address Data

types: 
  address:
    properties: 
      addressline1: string
      addressline2?: string
      city: string
      state: string
      zip: string
      country?: string 
